# Conditional statement
# nested elif
# name="dev"
# if name=="dev":
#     print("yes name is provided")
# else:
#     print("name is not provided")

# name="rahul"
# if name=="sahil":
#     print("yes name  rahul is provide")
# else:
#     print("name is not provided")


# name="aman"
# if name:
#     print(f"yes name {name} is provided")
# else:
#     print(f"name is not provided")    

# pre=int(input("enter your pre marks :"))
# if pre >= 400:
#     print("your are pass in pre and eligible for mains")
#     mains=int(input("enter your mains mark :"))
#     if mains >= 600:
#         print("you are pass in mains exam and selected for interview")
#         interview =int(input("Enter Your Interview Marks : "))
#         if interview >= 500:
#             print("you crack a interview and got a job")
#         else:
#             print("you are not crack a interview and you are not get a job")
#     else:
#         print("your are not pass in mains exam and not eligible for interview")
        
# else:
#     print("you are not pass in pre exam and not eligible for mains")


# name = "Dec"
# if condition:
#     print()
#     if condition2:
#         print()
#         if condition 3:
#             print()
#             if conditional 4:
#                 print()
#                 if condgh 5:
#                     print()
#                     if



#                 else:
#                     print()    
#             else:
#                 print()
#         else:
#             print()
    
#     else:
#         print()
# else:
#     print()
          


student_name=input("enter your name : ")
roll_number = int(input("enter your roll_number "))
pre_marks=int(input("enter your pre number "))
if pre_marks >450:
    print(f"you pass pre exam,you selected for mains exam")
    mains_exam=int(input("enter your mains number"))
    if mains_exam >550:
        print(f"you are pass mains eaxm,you selected for interview")
        interview=int(input("enter your number"))
        if interview >650:
           print(f"you are crack your interview,you are get a job")
        else:
            print(f"you are not crack your interview,your not get a job")    
    else:
        print(f"you are not pas n mains eaxm,you are not selected for interview")    

else:
    print(f"you are not pass pre exam,you are not selected for mains exam")




    

    

        
        
        




